name: Release

on:
    push:
        branches:
            - master
            - next
            - next-major
            - beta
            - alpha

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Install extra plugins
                run: npm i --no-save @semantic-release/changelog@6.0.1 @semantic-release/git@10.0.1

            -   name: Create a release
                uses: codfish/semantic-release-action@v1
                with:
                    plugins: |
                        ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/changelog', '@semantic-release/git', '@semantic-release/github']
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
